### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by AndroidNerd** [CameloeAnthony/MVPCommon#2]
When I build Gradle,I got a Error:No cached version listing for cn.leancloud.android:avoscloud-sdk:v3.+ available for offline mode.

**Comment by CameloeAnthony** [comment]
using Android Studio，go to File->Settings->Build, Execution, Deployment->Build tools->Gradle，then unCheck the offline work checkbox.        BTW,   I am Rearchitecting this project with Rxjava, SqlBrite,Dagger2 and many other new techniques these days . so this project may not be complete currently .
